name: Docker Build & Push

on:
  push:
    branches:
      - main
      
permissions:
  contents: read
  packages: write

jobs:
  build-and-push:
    permissions:
      contents: read
      packages: write
    name: Build & Push ${{ matrix.service }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        service:
          - auth-service
          - project-service
          - task-service
          - notification-service
          - frontend

    steps:
      - uses: actions/checkout@v6

      - name: Set lowercase repository name
        run: echo "REPO_LC=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Docker Buildx
        uses: docker/setup-buildx-action@8d2750c68a42422c14e847fe6c8ac0403b4cbd6f  # v3
        with:
          driver: docker

      - name: Login GitHub Container Registry
        uses: docker/login-action@c94ce9fb468520275223c153574b00df6fe4bcc9  # v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set image name
        run: |
          echo "IMAGE_NAME=$(echo '${{ github.repository }}' | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV

      - name: Promote dev image to main tags
        run: |
          IMAGE="ghcr.io/${{ env.IMAGE_NAME }}/${{ matrix.service }}"

          docker pull "$IMAGE:dev"

          docker tag "$IMAGE:dev" "$IMAGE:latest"
          docker tag "$IMAGE:dev" "$IMAGE:main"
          docker tag "$IMAGE:dev" "$IMAGE:sha-${{ github.sha }}"

          docker push "$IMAGE:latest"
          docker push "$IMAGE:main"
          docker push "$IMAGE:sha-${{ github.sha }}"